kind: ethereum/contract
name: MolochDAO
network:
source:
  address: ""
  abi: V1Moloch
  startBlock:
mapping:
  kind: ethereum/events
  apiVersion: 0.0.5
  language: wasm/assemblyscript
  entities:
    - Moloch
    - Member
  abis:
    - name: V1Moloch
      file: ./abis/V1Moloch.json
    - name: Guildbank
      file: ./abis/Guildbank.json
    - name: Erc20
      file: ./abis/Erc20.json
    - name: Erc20Bytes32
      file: ./abis/Erc20Bytes32.json
  eventHandlers:
    - event: "SummonComplete(indexed address,uint256)"
      handler: handleSummonCompleteMoloch
  file: ./src/legacy-mapping.ts
