kind: ethereum/contract
name: NeapolitanMinionTemplate
network:
source:
  abi: NeapolitanMinion
mapping:
  kind: ethereum/events
  apiVersion: 0.0.3
  language: wasm/assemblyscript
  file: ./src/neapolitan-minion-mapping.ts
  entities:
    - Moloch
    - Minion
    - Proposal
  abis:
    - name: NeapolitanMinion
      file: ./abis/NeapolitanMinion.json
  eventHandlers:
    - event: "ProposeAction(indexed bytes32,indexed uint256,uint256,address,uint256,bytes)"
      handler: handleProposeAction
    - event: "ExecuteAction(indexed bytes32,indexed uint256,uint256,address,uint256,bytes,address)"
      handler: handleExecuteAction
