kind: ethereum/contract
name: V21Factory
network:
source:
  address: ""
  abi: V21Factory
  startBlock:
mapping:
  kind: ethereum/events
  apiVersion: 0.0.5
  language: wasm/assemblyscript
  entities:
    - Register
  abis:
    - name: V21Factory
      file: ./abis/V21Factory.json
    - name: Erc20
      file: ./abis/Erc20.json
    - name: Erc20Bytes32
      file: ./abis/Erc20Bytes32.json
  eventHandlers:
    - event: >-
        SummonComplete(indexed
        address,address[],address[],uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[])
      handler: handleSummonV21
    - event: "Register(uint256,address,string,string,uint256)"
      handler: handleRegisterV21
  file: ./src/factory-mapping.ts
