kind: ethereum/contract
name: V2MinionFactory
network:
source:
  address: ""
  abi: MinionFactory
  startBlock:
mapping:
  kind: ethereum/events
  apiVersion: 0.0.5
  language: wasm/assemblyscript
  entities:
    - Moloch
    - Minion
  abis:
    - name: V1Moloch
      file: ./abis/V1Moloch.json
    - name: MinionFactory
      file: ./abis/V2MinionFactory.json
    - name: Minion
      file: ./abis/V2Minion.json
  eventHandlers:
    - event: "SummonMinion(indexed address,indexed address,string,string)"
      handler: handleSummonedV2Minion
  file: ./src/minion-factory-mapping.ts
